# Generated by Django 5.2.1 on 2025-05-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depart', to='app.department', to_field='department_name'),
        ),
    ]
