# Generated by Django 5.2 on 2025-05-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name_q', models.CharField(max_length=50)),
                ('cus_email_q', models.EmailField(max_length=254)),
                ('cus_query_q', models.CharField(max_length=150)),
            ],
        ),
    ]
