# Generated by Django 5.2 on 2025-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_product_name', models.CharField(max_length=70)),
                ('db_product_discription', models.CharField(max_length=400)),
                ('db_product_discription2', models.CharField(max_length=400)),
                ('db_product_previous_price', models.IntegerField()),
                ('db_product_offer_percentage', models.IntegerField()),
                ('db_product_real_price', models.IntegerField()),
                ('db_product_image1', models.ImageField(upload_to='image')),
                ('db_product_image2', models.ImageField(upload_to='image')),
                ('db_product_image3', models.ImageField(upload_to='image')),
                ('db_product_image4', models.ImageField(upload_to='image')),
                ('db_product_image5', models.ImageField(upload_to='image')),
                ('db_product_image6', models.ImageField(upload_to='image')),
            ],
        ),
    ]
