# Generated by Django 5.2 on 2025-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dynamiccards'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccards',
            name='db_product_catagurays',
            field=models.CharField(default='grocery', max_length=100),
        ),
    ]
