# Generated by Django 5.2 on 2025-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dynamiccards_db_product_catagurays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccards',
            name='db_product_catagurays',
            field=models.CharField(max_length=100),
        ),
    ]
