# Generated by Django 5.2.1 on 2025-05-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcompany',
            old_name='name',
            new_name='model_name',
        ),
    ]
