# Generated by Django 5.2.1 on 2025-05-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_carcompany_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcompany',
            old_name='model_name',
            new_name='name',
        ),
    ]
