# Generated by Django 5.2 on 2025-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'NewName'},
        ),
    ]
