# Generated by Django 5.2 on 2025-04-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': 'NewName', 'verbose_name_plural': 'Student'},
        ),
    ]
