# Generated by Django 5.2 on 2025-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_detail', models.CharField(max_length=200)),
                ('stu_phone', models.IntegerField()),
                ('stu_dob', models.DateField()),
                ('stu_quali', models.CharField(max_length=50)),
                ('stu_gender', models.CharField(max_length=60)),
                ('stu_image', models.ImageField(upload_to='image')),
                ('stu_resume', models.FileField(upload_to='image')),
                ('stu_pass', models.CharField(max_length=50)),
                ('stu_cpass', models.CharField(max_length=50)),
            ],
        ),
    ]
