# Generated by Django 5.2 on 2025-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Newname', 'verbose_name_plural': 'Student'},
        ),
    ]
