# Generated by Django 5.2 on 2025-05-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='aadhar'),
        ),
    ]
