# Generated by Django 5.2 on 2025-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstmer_name', models.CharField(max_length=50)),
                ('cstmer_email', models.EmailField(max_length=254, unique=True)),
                ('cstmer_pass', models.CharField(max_length=50)),
                ('cstmer_cpass', models.CharField(max_length=50)),
                ('cstmer_image', models.ImageField(upload_to='image')),
                ('cstmer_phone', models.IntegerField()),
                ('cstmer_city', models.CharField(max_length=50)),
            ],
        ),
    ]
