# Generated by Django 5.2.1 on 2025-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='image')),
                ('city', models.CharField(max_length=70)),
                ('about', models.CharField(max_length=70)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
