# Generated by Django 5.2 on 2025-05-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_department_remove_user_aadhar_no_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField(unique=True)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contect', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('aadhar_no', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='aadhar')),
            ],
        ),
    ]
