# Generated by Django 5.2 on 2025-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aadhar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fule_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicles_name', models.CharField(max_length=50, unique=True)),
                ('Fule_name', models.ManyToManyField(related_name='vehical', to='app.fule')),
            ],
        ),
    ]
