# Generated by Django 5.2 on 2025-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fule_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='Vehicles_name',
            field=models.CharField(max_length=50),
        ),
    ]
