# Generated by Django 5.2 on 2025-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
