# Generated by Django 5.2 on 2025-05-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar',
            old_name='aadhar_no',
            new_name='aadhar',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='aadhar',
            new_name='aadhar_no',
        ),
    ]
