# Generated by Django 5.2 on 2025-05-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_aadhar_no_aadhar_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='aadhar'),
        ),
    ]
